[param]
interface_type = "Uart"
comport_uart = "COM11"
chip = "BL616/618"
chip_name = "bl616"
chip_type = "bl616"
speed_uart = "2000000"
speed_jlink = "1000"
erase = "1"
skip_mode = "0x0, 0x0"
boot2_isp_mode = "0"

[check_box]
efuse = false

[input_path]
efuse = ""
config = "C:/Users/User/AppData/Local/Temp/arduino/sketches/A4B93F2CB9A7D267AC9B6617111206D2/flash_prog_cfg.ini"

[boot2]
addr = "0x000000"
path = "C:\\Users\\User\\AppData\\Local\\Temp\\arduino\\sketches\\A4B93F2CB9A7D267AC9B6617111206D2\\boot2_bl616_isp_release_v8.1.1.bin"

[partition]
addr = "0xE000"
path = "C:\\Users\\User\\AppData\\Local\\Temp\\arduino\\sketches\\A4B93F2CB9A7D267AC9B6617111206D2\\partition.bin"

[FW]
addr = "0x10000"
path = "C:\\Users\\User\\AppData\\Local\\Temp\\arduino\\sketches\\A4B93F2CB9A7D267AC9B6617111206D2\\WiFiClientConnect.ino.bin"

[mfg]
addr = "0x210000"
path = "C:\\Users\\User\\AppData\\Local\\Temp\\arduino\\sketches\\A4B93F2CB9A7D267AC9B6617111206D2\\mfg_bl616_gu_07f814fed_v2.30.bin"
